### ISSUE TITLE
where is content?

### ISSUE THREAD

**Issue by Gakiii** [JNUFoodZZT/electric-field#1]
where is your code?

**Comment by JNUFoodZZT** [comment]
my mind

--------------原始邮件--------------
发件人："JakcyHu ***@***.***&gt;;
发送时间：2022年4月23日(星期六) 下午3:00
收件人："JNUFoodZZT/electric-field" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[JNUFoodZZT/electric-field] where is content? (Issue #1)
-----------------------------------

 

 
where is your code?
